[project]
name = "a-global-presence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.37.32",
    "requests>=2.32.3",
]

[tool.uv.workspace]
members = ["layer"]
